# Generated by Django 4.2.13 on 2024-06-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='album',
            table='apps_album',
        ),
        migrations.AlterModelTable(
            name='albummemory',
            table='apps_album_memory',
        ),
    ]
