# Generated by Django 4.2.13 on 2024-06-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_alter_album_table_alter_albummemory_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='albummemory',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
