# Generated by Django 4.2.13 on 2024-06-04 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_albummemory_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albummemory',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='album',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
