# Generated by Django 4.2.13 on 2024-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0004_remove_albummemory_updated_at_album_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': '앨범'},
        ),
    ]
