FROM python:3.11

WORKDIR /usr/src/app

# poetry
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

# copy files
COPY ./apps ./apps
COPY ./config ./config
COPY ./manage.py .
COPY .env .

RUN poetry run python manage.py collectstatic

CMD ["poetry", "run", "gunicorn", "--bind", "0.0.0.0:8080", "config.wsgi:application"]