FROM python:3.11

WORKDIR /usr/src/app

# env
COPY .env .
RUN export $(cat .env | xargs)

# poetry
RUN pip install poetry
COPY pyproject.toml poetry.lock ./
RUN poetry install --no-root

# copy files
COPY ./apps ./apps
COPY ./config ./config
COPY ./manage.py .

COPY ./docker-entrypoint.django.sh ./
RUN chmod +x ./docker-entrypoint.django.sh
ENTRYPOINT ./docker-entrypoint.django.sh