# Generated by Django 4.2.13 on 2024-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': '사용자'},
        ),
        migrations.AlterModelTable(
            name='user',
            table='apps_user',
        ),
    ]
