# Generated by Django 4.2.13 on 2024-06-04 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0002_memory_is_liked_delete_memorylike'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='memory',
            table='apps_memory',
        ),
    ]
