# Generated by Django 4.2.13 on 2024-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('memory', '0003_alter_memory_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='memory',
            options={'verbose_name_plural': '추억'},
        ),
    ]
