# Generated by Django 4.2.13 on 2024-06-04 12:29

import apps.upload.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('memory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file_type', models.CharField(choices=[('PHOTO', 'PHOTO'), ('VIDEO', 'VIDEO')], max_length=10)),
                ('file', models.FileField(upload_to=apps.upload.models.upload_to)),
                ('memory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memory.memory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
