# Generated by Django 4.2.13 on 2024-06-10 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_alter_upload_file_alter_upload_memory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='upload',
            options={'verbose_name_plural': '업로드'},
        ),
        migrations.AlterModelTable(
            name='upload',
            table='apps_upload',
        ),
    ]
